### PR TITLE
Create Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by Lavyk**

### CODE REVIEW

**Review by FabianSchurig — COMMENTED** [review]
Thanks for the work. Just testing an automated Copilot review:

Result:
The translation seems to be well done overall, but there are a few minor improvements that could be made:

**File: locales/pt-BR.json**

- "register" -> "name_info": The phrase "O comprimento máximo é de 30 caracteres. Seu nome será visível para todos. Você pode alterar seu nome a qualquer momento." could be improved to "O comprimento máximo permitido é de 30 caracteres. Seu nome será visível para todos os usuários. Você pode alterar seu nome a qualquer momento." for clarity.

- "highscore" -> "column" -> "cnt": "CNT" is not a common abbreviation in Portuguese. Consider changing it to a full word or a more common abbreviation.

- "live" -> "friends_without_bets": The phrase "Amigos sem apostas (clique para mostrar)" could be improved to "Amigos que não fizeram apostas (clique para mostrar)" for better understanding.

- "mybets" -> "edit_bet_until": The phrase "Altere sua aposta até {{date}}." could be improved to "Você pode alterar sua aposta até {{date}}." for better understanding.

- "extra_bet" -> "team_info": The phrase "Escolha 1 time para {{name}}." could be improved to "Escolha um time para {{name}}." as it's more natural to use "um" instead of "1" in this context.

- "settings" -> "name": The phrase "Nome (3 a 30 caracteres)" could be improved to "Nome (mínimo de 3 e máximo de 30 caracteres)" for better understanding.

These are minor improvements and the overall translation seems to be well done. Great job! 👍

**Comment by Lavyk** [comment]
So that I can translate it in the best possible way, could you describe what CNT would be?

**Comment by syxolk** [comment]
> So that I can translate it in the best possible way, could you describe what CNT would be?

CNT and PTS is used on the highscore page, as abbreviations for "count" and "points".

**Comment by Lavyk** [comment]
We commonly call the game count "Jogos" or the abbreviation "J". Explicitly for a better popular understanding, "Jogos" fits better in this context. The Portuguese of the streets hahaha

**Review by syxolk — APPROVED** [review]

**Pull request merged**
