### PR TITLE
More points on final phase matches

### PR DESCRIPTION
**Pull request by AlexanderSachin**
After fixing the regressions:

The main enhancement is the addition of the coefficient according to match type: This allow to give more points in final phase. This coefficient can be set to 1 to keep he current behavior.

I also added, by configuration, the possibility to send confirmation emails with SMTP protocol by connecting to a SMTP server.

Finally i added the link to Admin page in the navbar according to user profile.

### CODE REVIEW

**Comment by vincentbriglia** [comment]
cebb8a9 - people might have signed up through social only, in which case their email might not be set nor will it need to be confirmed.

**Comment by tuudik** [comment]
Why this pull request has not been accepted? :(

**Comment by syxolk** [comment]
Thanks for contributing so much, @AlexanderSachin. I'm currently rather busy with other stuff but I might merge this in the next days.

**Comment by syxolk** [comment]
Score factors have been implemented for a while now.

**Pull request closed without merging**
